# Generated by Django 3.0.7 on 2020-06-30 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('look_back', models.IntegerField(default=10)),
                ('low_sma', models.IntegerField(default=10)),
                ('high_sma', models.IntegerField(default=34)),
                ('max_single_pos', models.FloatField(default=0.1)),
                ('sma_diff', models.FloatField(default=0)),
                ('sma_slope', models.FloatField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-price_date']},
        ),
    ]
