# Generated by Django 3.0.7 on 2020-07-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smabacktest',
            name='sharpe_ratio',
            field=models.FloatField(default=0),
        ),
    ]
