# Generated by Django 3.0.7 on 2020-08-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='unique stock if in portfolio',
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(condition=models.Q(close_date__isnull=True), fields=('stock', 'portfolio'), name='unique stock if in portfolio'),
        ),
    ]
