# Generated by Django 3.0.7 on 2020-07-22 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200721_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='executed_at',
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 15, 54, 55, 745704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='api.Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 15, 54, 55, 742319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 15, 54, 55, 745120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sma_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='api.SMAPosition'),
        ),
        migrations.AlterUniqueTogether(
            name='sellorder',
            unique_together={('user', 'price_date', 'position', 'stock', 'portfolio')},
        ),
        migrations.DeleteModel(
            name='PendingOrder',
        ),
        migrations.RemoveField(
            model_name='sellorder',
            name='executed_at',
        ),
    ]
