# Generated by Django 3.0.7 on 2020-08-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200811_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='api.Position'),
        ),
    ]
