# Generated by Django 3.0.7 on 2020-09-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200925_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neuralnetwork',
            options={'ordering': ['-test_accuracy']},
        ),
    ]
