# Generated by Django 3.0.7 on 2020-07-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_smabacktest_sharpe_ratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smabacktest',
            options={'ordering': ['-score']},
        ),
        migrations.AlterUniqueTogether(
            name='smaposition',
            unique_together={('price_date', 'stock', 'model')},
        ),
    ]
