# Generated by Django 3.0.7 on 2020-08-01 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200801_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
