# Generated by Django 3.0.7 on 2020-07-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200711_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.SMAModel'),
        ),
    ]
