# Generated by Django 3.0.7 on 2020-07-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200723_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='canceled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='close_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='closed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
