# Generated by Django 3.0.7 on 2020-09-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200925_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pos_size',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stop_loss',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='take_profit',
            field=models.FloatField(default=None),
        ),
    ]
