# Generated by Django 3.0.7 on 2020-08-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_buyorder_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='smaposition',
            name='high_sma',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='smaposition',
            name='low_sma',
            field=models.FloatField(default=0),
        ),
    ]
