# Generated by Django 3.0.7 on 2020-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200823_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='smaposition',
            name='close',
            field=models.FloatField(default=0),
        ),
    ]
