# Generated by Django 3.0.7 on 2020-08-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfoliohistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='date',
        ),
    ]
