# Generated by Django 3.0.7 on 2020-09-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200926_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='pos_size',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stop_loss',
            field=models.FloatField(default=0.05),
        ),
    ]
