# Generated by Django 3.0.7 on 2020-08-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_portfoliohistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliohistory',
            options={'ordering': ['updated_at']},
        ),
    ]
