# Generated by Django 3.0.7 on 2020-08-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_smaposition_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='demo_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='real_live',
            field=models.BooleanField(default=False),
        ),
    ]
