# Generated by Django 3.0.7 on 2020-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200711_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executed_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
