# Generated by Django 3.0.7 on 2020-07-23 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200722_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sellorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='buyorder',
            name='current_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 1, 45, 31, 375763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 1, 45, 31, 372373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 1, 45, 31, 375181, tzinfo=utc)),
        ),
    ]
