# Generated by Django 3.0.7 on 2020-09-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200926_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='pos_size',
            field=models.FloatField(default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stop_loss',
            field=models.FloatField(default=0.05, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='take_profit',
            field=models.FloatField(default=None, null=True),
        ),
    ]
