# Generated by Django 3.0.7 on 2020-08-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200824_0022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smaposition',
            unique_together={('price_date', 'stock', 'model', 'sma_backtest')},
        ),
    ]
