# Generated by Django 3.0.7 on 2020-07-23 02:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200723_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='executed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='executed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 2, 13, 26, 367661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 2, 13, 26, 363688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 2, 13, 26, 367055, tzinfo=utc)),
        ),
    ]
