# Generated by Django 3.0.7 on 2020-08-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200802_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliohistory',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
