# Generated by Django 3.0.7 on 2020-09-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200824_1217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('stock', 'portfolio', 'open_date', 'open_rate', 'num_of_shares', 'total_investment', 'stop_loss_rate', 'take_profit_rate', 'close_rate', 'close_date')},
        ),
    ]
