# Generated by Django 3.0.7 on 2020-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200802_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='terminated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
