# Generated by Django 3.0.7 on 2020-08-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_buyorder_terminated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliohistory',
            options={'ordering': ['-created_at']},
        ),
    ]
