# Generated by Django 3.0.7 on 2020-09-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200901_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='latent_p_l',
            field=models.FloatField(default=None, null=True),
        ),
    ]
