# Generated by Django 3.0.7 on 2020-07-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200713_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.SMAPosition'),
        ),
    ]
