# Generated by Django 3.0.7 on 2020-09-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_portfoliohistory_latent_p_l'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliohistory',
            options={},
        ),
    ]
