# Generated by Django 3.0.7 on 2020-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200713_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_loss',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='take_profit',
            field=models.FloatField(default=None, null=True),
        ),
    ]
