# Generated by Django 3.0.7 on 2020-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200713_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='submited_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
