# Generated by Django 3.0.7 on 2020-07-13 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200713_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(default=None)),
                ('num_of_shares', models.IntegerField(default=None)),
                ('order_price', models.FloatField(default=None, null=True)),
                ('stop_loss', models.FloatField(default=None, null=True)),
                ('take_profit', models.FloatField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('submited_at', models.DateTimeField(default=None, null=True)),
                ('executed_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['-price_date'],
            },
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.IntegerField(default=None)),
                ('price_date', models.DateField(default=None)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('submited_at', models.DateTimeField(default=None, null=True)),
                ('executed_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['-price_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='order_constraint',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='position',
            new_name='sma_position',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('price_date', 'sma_position', 'stock')},
        ),
        migrations.AddField(
            model_name='sellorder',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='api.Position'),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='sma_position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='api.SMAPosition'),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='api.Stock'),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='sma_position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='api.SMAPosition'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='api.Stock'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sellorder',
            unique_together={('price_date', 'sma_position', 'position', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='buyorder',
            unique_together={('price_date', 'sma_position', 'stock')},
        ),
    ]
