# Generated by Django 3.0.7 on 2020-07-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200713_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
