# Generated by Django 3.0.7 on 2020-07-13 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20200713_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 35, 34, 288313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='sma_position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='api.SMAPosition'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 35, 34, 285063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 35, 34, 287709, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='buyorder',
            unique_together={('user', 'price_date', 'sma_position', 'stock')},
        ),
    ]
