# Generated by Django 3.0.7 on 2020-07-13 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200713_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='api.Portfolio'),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='api.Portfolio'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 57, 36, 404243, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='sma_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='api.SMAPosition'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 57, 36, 400886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 57, 36, 403590, tzinfo=utc)),
        ),
    ]
