# Generated by Django 3.0.7 on 2020-07-13 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200713_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='orders_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 17, 16, 13, 922893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 17, 16, 13, 919510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 17, 16, 13, 922234, tzinfo=utc)),
        ),
    ]
