# Generated by Django 3.0.7 on 2020-07-14 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20200713_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 10, 15, 6, 488398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 10, 15, 6, 487743, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='buyorder',
            unique_together={('user', 'price_date', 'sma_position', 'stock', 'portfolio')},
        ),
        migrations.AlterUniqueTogether(
            name='sellorder',
            unique_together={('price_date', 'sma_position', 'position', 'stock', 'portfolio')},
        ),
    ]
