# Generated by Django 3.0.7 on 2020-07-18 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200717_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol']},
        ),
        migrations.AddField(
            model_name='smabacktest',
            name='profitable_buy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smabacktest',
            name='unprofitable_buy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 21, 51, 45, 327360, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 21, 51, 45, 326688, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('symbol',)},
        ),
    ]
